# Generated by Django 5.1.4 on 2024-12-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('over_fi', '0003_overfi_legal_ball_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overfi',
            name='legal_ball_numbers',
        ),
    ]
