# Generated by Django 5.1.4 on 2024-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batting', '0003_batting_balls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='best_score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
