# Generated by Django 5.1.4 on 2024-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fielding', '0002_fielding_player'),
        ('match', '0004_match_is_match_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielding',
            name='match',
        ),
        migrations.AddField(
            model_name='fielding',
            name='match',
            field=models.ManyToManyField(blank=True, related_name='fielding', to='match.match'),
        ),
    ]
