# Generated by Django 5.1 on 2024-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('matches', models.IntegerField(blank=True, default=0, null=True)),
                ('won', models.IntegerField(blank=True, default=0, null=True)),
                ('lost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
