# Generated by Django 5.1 on 2024-08-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(blank=True, default=0, null=True)),
                ('innings', models.IntegerField(blank=True, default=0, null=True)),
                ('overs', models.FloatField(blank=True, default=0.0, null=True)),
                ('madiens', models.IntegerField(blank=True, default=0, null=True)),
                ('wickets', models.IntegerField(blank=True, default=0, null=True)),
                ('runs', models.IntegerField(blank=True, default=0, null=True)),
                ('best_bowling', models.IntegerField(blank=True, default=0, null=True)),
                ('economy_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('wides', models.IntegerField(blank=True, default=0, null=True)),
                ('no_balls', models.IntegerField(blank=True, default=0, null=True)),
                ('dot_balls', models.IntegerField(blank=True, default=0, null=True)),
                ('tetra_wickets', models.IntegerField(blank=True, default=0, null=True)),
                ('penta_wickets', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling', to='player.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling', to='team.team')),
            ],
        ),
    ]
