# Generated by Django 5.1.4 on 2024-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_bowling_balls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowling',
            name='best_bowling',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
