# Generated by Django 5.1 on 2024-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_types', models.CharField(blank=True, choices=[('Wide', 'WD'), ('No_ball', 'NB'), ('Byes', 'BYES'), ('Leg_byes', 'LB'), ('Dot_ball', 'DB'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'FOUR'), ('Five', 'Five'), ('Six', 'SIX'), ('Catch', 'CATCH'), ('Run_out', 'RUN OUT'), ('Leg_before_wicket', 'LBW'), ('Handled_the_ball', 'HTB'), ('Obstructing_the_field', 'OTF'), ('Overthrow', 'OT'), ('Out', 'OUT'), ('Stumped', 'STUMPED'), ('Hit_wicket ', 'HW')], max_length=100, null=True)),
                ('runs', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0, null=True)),
            ],
        ),
    ]
