# Generated by Django 5.1 on 2024-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='ball_types',
            field=models.CharField(blank=True, choices=[('Wide', 'WD'), ('No_ball', 'NB'), ('Byes', 'BYES'), ('Leg_byes', 'LB'), ('Dot_ball', 'DB'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'FOUR'), ('Five', 'Five'), ('Six', 'SIX'), ('Catch_out', 'CATCH OUT'), ('Run_out', 'RUN OUT'), ('Leg_before_wicket', 'LBW'), ('Handled_the_ball', 'HTB'), ('Obstructing_the_field', 'OTF'), ('Overthrow', 'OT'), ('Bowled_out', 'BOWLED OUT'), ('Stumping', 'STUMPING'), ('Hit_wicket ', 'HW')], max_length=100, null=True),
        ),
    ]
