# Generated by Django 5.1 on 2024-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madien_over', models.IntegerField(blank=True, null=True)),
                ('run', models.IntegerField(blank=True, null=True)),
                ('wicket', models.IntegerField(blank=True, null=True)),
                ('economy_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
