# Generated by Django 5.1 on 2024-09-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler', '0003_bowler_nth_ball_bowler_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='nth_ball',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bowler',
            name='over',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
