# Generated by Django 5.1 on 2024-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler', '0004_alter_bowler_nth_ball_alter_bowler_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='economy_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='bowler',
            name='madien_over',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bowler',
            name='run',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowler',
            name='wicket',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
