# Generated by Django 5.1 on 2024-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler', '0005_alter_bowler_economy_rate_alter_bowler_madien_over_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='run',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
