# Generated by Django 5.1 on 2024-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler', '0006_alter_bowler_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='wicket',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
