# Generated by Django 5.1 on 2024-08-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fielder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(default=0, null=True)),
                ('ball', models.FloatField(default=0.0, null=True)),
                ('four', models.IntegerField(default=0, null=True)),
                ('six', models.IntegerField(default=0, null=True)),
                ('strike_rate', models.FloatField(default=0.0, null=True)),
                ('is_out', models.BooleanField(default=False)),
                ('is_hitting', models.BooleanField(default=False)),
                ('catch_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catch_by_batsman', to='fielder.fielder')),
            ],
        ),
    ]
