# Generated by Django 5.1 on 2024-09-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batsman', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batsman',
            name='is_hitting',
        ),
        migrations.AddField(
            model_name='batsman',
            name='how_wicket_fall',
            field=models.CharField(blank=True, choices=[('bowled', 'Bowled'), ('catch_out', 'Catch Out'), ('run_out', 'Run Out'), ('stumping', 'Stumping'), ('lbw', 'LBW'), ('hit_wicket', 'Hit Wicket')], max_length=30, null=True),
        ),
    ]
