# Generated by Django 5.1 on 2024-09-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batsman', '0003_remove_batsman_is_hitting_batsman_how_wicket_fall'),
        ('fielder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batsman',
            name='stumping_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stumping_by_batsman', to='fielder.fielder'),
        ),
    ]
