# Generated by Django 5.1 on 2024-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batsman', '0004_batsman_stumping_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batsman',
            name='how_wicket_fall',
            field=models.CharField(blank=True, choices=[('bowled', 'Bowled'), ('catch_out', 'Catch Out'), ('run_out_striker', 'Run Out'), ('run_out_non_striker', 'Run Out'), ('stumping', 'Stumping'), ('lbw', 'LBW'), ('hit_wicket', 'Hit Wicket')], max_length=30, null=True),
        ),
    ]
