# Generated by Django 5.1 on 2024-08-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batsman', '0002_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallOfWickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('wicket', models.IntegerField(blank=True, default=0, null=True)),
                ('batsman', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batsman', to='batsman.batsman')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fall_of_wickets', to='match.match')),
            ],
        ),
    ]
