# Generated by Django 5.1.4 on 2024-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0002_remove_partnerships_batsman1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerships',
            name='non_striker_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnerships',
            name='striker_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
