# Generated by Django 5.1 on 2024-09-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fielder', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielder',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='player.player'),
        ),
    ]
