# Generated by Django 5.1 on 2024-08-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batsman', '0001_initial'),
        ('bowler', '0001_initial'),
        ('over_fi', '0001_initial'),
        ('over_si', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_over', models.IntegerField(blank=True, default=5, null=True)),
                ('innings', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], default='1st', max_length=20, null=True)),
                ('first_innings_run_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('first_innings_run', models.IntegerField(blank=True, default=0, null=True)),
                ('first_innings_wicket', models.IntegerField(blank=True, default=0, null=True)),
                ('second_innings_run_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('second_innings_run', models.IntegerField(blank=True, default=0, null=True)),
                ('second_innings_wicket', models.IntegerField(blank=True, default=0, null=True)),
                ('nth_ball', models.IntegerField(blank=True, default=0, null=True)),
                ('elected', models.CharField(blank=True, choices=[('Bat', 'Batting'), ('Bowl', 'Bowling')], default='Bat', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_bowler', to='bowler.bowler')),
                ('first_innings_over', models.ManyToManyField(blank=True, related_name='fi_match', to='over_fi.overfi')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_non_striker_batsman', to='batsman.batsman')),
                ('second_innings_over', models.ManyToManyField(blank=True, related_name='si_match', to='over_si.oversi')),
                ('striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_striker_batsman', to='batsman.batsman')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='team.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team', to='team.team')),
                ('toss_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='team.team')),
            ],
        ),
    ]
