# Generated by Django 5.1 on 2024-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_innings_nth_over',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='second_innings_nth_over',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
