# Generated by Django 5.1 on 2024-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_first_innings_nth_over_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(blank=True, default='First innings running', max_length=100, null=True),
        ),
    ]
