# Generated by Django 5.1 on 2024-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_match_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
