# Generated by Django 5.1.4 on 2024-12-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_is_match_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_innings_nth_ball',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='second_innings_nth_ball',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
